# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://flamelily.github.io
title: Flamelily IT Computer support and Web development
email: info@flamelily.co.uk
author: Flamelily IT
description: > # "Write an awesome description for your new site here. 
  Flamelily I.T offer many services at reasonable prices. We are Voice over IP specialists and offer many internet telephony options. 
  We offer Website and email hosting for small businesses and individuals. We offer Web design and development using the latest web technologies.
copyright: 'Copyright &copy; 2016 Flamelily IT. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/flamelilyit
  - title: github
    url: https://github.com/flamelily
  - title: linkedin
    url: https://www.linkedin.com/company/flamelily-it
